### ISSUE TITLE
Bug: Long press on Galaxy reaction menu is cut off 

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#1146]
### Describe the bug

Seen in 2.0.7, should fix for 2.0.8

![image](https://github.com/user-attachments/assets/92d33ec1-a9ab-4c7d-9be6-7d69bd92a2e7)

**Comment by lourou** [comment]
@alexrisch after many tests, including tests on various sets of physical devices, I managed to reproduce this on some Samsung Galaxy devices, only on API 30 (Android 11) and API 31 (Android 12). From API 32 onwards, the issue is not visible.

I'll use Firebase Blaze Plan to debug on a remote physical device: Galaxy A51 on API 31 (Android 12).

Will keep you posted!

![CleanShot 2024-11-06 at 16 42 01@2x](https://github.com/user-attachments/assets/413cf47d-766f-40a1-a961-d0044125ba20)

**Comment by lourou** [comment]
Emojis now fit in the picker on all devices:
<img src="https://github.com/user-attachments/assets/20d91d4b-a480-4dfa-baa6-cac47b66ef3e" width="350" />
