### ISSUE TITLE
Transactions Frames Support

### ISSUE THREAD

**Issue by nplasterer** [ephemeraHQ/converse-app#17]
Lets add the ability for transaction frames in chat.
- [ ] Transaction frame rendering
- [ ] Transaction frame working
- [ ] Cautionary warning (needs design)
- [ ] Transaction simulation (needs design)

**Comment by alexrisch** [comment]
There will always be a warning when leaving the app

The simulation library we are looking at is https://blowfish.xyz/

**Comment by alexrisch** [comment]
Awaiting some product design decisions on the UX of choosing a wallet to sign the transaction

**Comment by nmalzieu** [comment]
@alexrisch should we split that issue in multiple issues?

I see that you have started investigation on the simulation for txs, do you want to take on the backend / simulation part and I continue work on the triggering of it from Converse once I'm done with wallet selection for revocation?

**Comment by covrter** [comment]
Will need y'all to walk me through this once before I dive in. I get it but would love a live demo (of peer apps, of what we're thinking, etc.)

**Comment by covrter** [comment]
Hi team! Chatted with @saulmc and I don't think we need to innovate here (yet) — which is to say, let's follow the flow/patterns that Farcaster has established for this interaction (wallet selection, warnings, simulation).

I expect that we'll upgrade the UI here at some point (to match styles which are yet TBD), but for now applying UI patterns/styles that we already use is AOK.

Holler when specific questions come up, and I'll unblock!

**Comment by alexrisch** [comment]
@nmalzieu Yep can do! I have a call scheduled with Blowfish tomorrow to get the API Key that's needed.
Just want to confirm I will create an endpoint on that backend that will run the simulation
Backend would need the transaction and the address of the user

Backend would return estimated changes, message, flagged boolean to display an error, or maybe a status of "ok", "warn", "error", will have a better feeling after the call

**Comment by saulmc** [comment]
On the multi-acccount UX challenge that @nmalzieu flagged.

In the single embedded wallet world we are moving towards, multiple account connections will be under the hood and abstracted into a combined inbox. External wallets can be connected explicitly for the purpose of top-up transactions.

With this view of the future, I suggest we bypass the multi-account issue by allowing a user to connect and designate an external transaction wallet. This could be one of their XMTP account wallets, but doesn't have to be. It's not weird because no expectation has been set that your currently active account is the wallet that is transaction.

@covrter does this jive with your thinking?

**Comment by covrter** [comment]
I think so. Let me write it out so that I can test my understanding. I think we're saying:

The wallet that I'm using as my chat identity MIGHT NOT BE the wallet I want to "use the Frame" with. And we're AOK with that. For example:

- I'm chatting with as andrew.eth but see a Mint action (in a frame) and would prefer to acquire it with a different wallet, say andrewvault.eth
- I see a Cointoss bet in the chat and my courter.eth (chat wallet) is broke but I want to fund the bet quick, so I can opt to use andrewcash.eth to transact with the frame instead.

This feels good to me — it gives the user maximum control, and puts shared responsibility on apps (chat and external wallet) for making clear WHICH wallet/identity is doing what.

Is that right?

**Comment by saulmc** [comment]
> A case it could be weird is:

Yes, understood! The product copy and design must be effective at conveying "the wallet you have connected to transact with" is a totally separate concept from "the wallet you are currently messaging with".

> FWIW, I don't think this changes once we have embedded wallets. There will be times (most of the time?), I'll want to interact with tx frames with a specific wallet that is not the current embedded wallet (because you'll want to collect your NFTs on your main wallet or you'll have access to specific frames because you have some assets).

Kind of! Our hypothesis is that consumer crypto is moving to a world where each person's identity and assets exist across a collection of wallets and chains that are largely invisible to them -- not concentrated in one main wallet that they identify with. There is definitely still a place for a core "vault" wallet for NFT collection/speculation, but this is overkill for minting as a social action (e.g. in Zora's new app) and unnecessary to use for things like payments, wagers, and even short-term memecoin flipping.

We could be very wrong about this!

**Comment by covrter** [comment]
> We could be very wrong about this!
That's what makes it fun!

All of the above makes sense y'all. Wild new world we get to help build here :)

**Comment by nmalzieu** [comment]
I have a working local flow of
- click on a tx frame
- open the drawer to select external wallet app (if none is currently connected)
- switch to the right chain (if needed)
- trigger tx
- send triggered tx hash to the frame for validation

**What is still needed**

@alexrisch on the tech side, do you think we could have a working simulation API in the backend this week or it's going to be short?

@saulmc @covrter on the UX side, we need a more complete flow

- a drawer before triggering the tx to show the simulation, currently linked wallet, ability to switch wallet if needed (see warpcast screenshot below)
-  a screen when we come back from the wallet after having triggered, to show a loader while we wait until the transaction is on the blockchain (or failed) so we can send it to the frame developer

![Image](https://github.com/user-attachments/assets/cf24f7cf-a0a6-402b-8f72-81b30430e655)

**Comment by covrter** [comment]
Thank you @nmalzieu ! Will get those new screens prepared for you — probably Thurs (deep in design system stuff today)

**Comment by alexrisch** [comment]
Closing this out as the feature branch is merged in 2.0.8
