### ISSUE TITLE
Feedback when I try to message myself or add myself to group

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#177]

**Comment by darickdang** [comment]
When a user has multiple identities connected (or not connected), they may forget which account they're currently messaging from so their own account should show up in the search results but it should say "You" instead of "Chat"

<img width="1022" alt="#177 - Feedback when I try to message myself or add myself to group" src="https://github.com/user-attachments/assets/383a8025-dbef-4660-b96a-a58d96faba9e">

Zeplin: [https://app.zeplin.io/project/668c5499777e4ac004a04f97/screen/66cf5fb3b41d21c0b6ba74c3](https://app.zeplin.io/project/668c5499777e4ac004a04f97/screen/66cf5fb3b41d21c0b6ba74c3)

**Comment by alexrisch** [comment]
This seems like a good time to move the `components/Search/ProfileSearch.tsx` & `components/Search/ProfileSearchItem.tsx` to our new design system/pattern as well as some clean up with screens/NewConversation/NewConversation.tsx

Dev Direction:

Move the referenced files into the new suggested folder pattern from the ADR
```
features/
├── search/
│   │   ├── components/
│   │   │   ├── SearchBar.tsx
│   │   │   ├── ProfileSearchItem.tsx
│   │   │   └── NoResult.tsx
│   │   ├── screens/
│   │   │   └── ProfileSearch.tsx
│   │   ├── navigation/
│   │   │   └── SearchNav.tsx
│   │   ├── hooks/
│   │   │   └── useSearchHooks.ts
│   │   ├── utils/
│   │   │   ├── search.ts
│   │   │   └── lens.ts
│   │   └── data/
│   │       └── store/
│   │           └── searchStore.ts
```

Also we should update the strings to be translated instead

Finally, when the address is the current account we should match the above design with a "You"
