### ISSUE TITLE
Long 1:1 conversations load incrementally from top after reconnecting account

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#352]
**Expected**
Whenever I enter a conversation, I am shown the latest messages.

**Actual**
After reconnecting my account and opening my conversation with Pol, I watched as new messages loaded into the conversation from oldest-to-newest for about 30 seconds.

**Repro**
After reconnecting your account with the app, navigate to a long-running 1:1 conversation.

**Comment by nmalzieu** [comment]
@saulmc I don't think this is a bug! It's the way the sync process works currently for 1:1 conversations. We need to process data from oldest to latest because most recent messages might reference older messages (reactions / replies).

When reconnecting the account to the app (which in real life happens only once, during onboarding), we used to show a "Syncing..." next to the activity indicator to show that this was happening. Now the string has been removed so it might look like an infinite spinner.

What would you expect?

**Comment by saulmc** [comment]
Got it. So this is specific to loading v2 conversations?

**Comment by nmalzieu** [comment]
Well yeah because for v3 we have no way to load older messages.
But when we have message history it will be kind of the same, but you will probably see everything appear at once

What's bothering you? If it's the fact that they appear by chunk, we could just block the UI until all messages have synced, but it's really annoying because it's really slow

**Comment by saulmc** [comment]
That might help, but since it's only a v2 problem, I don't think it's worth spending time on!
