### ISSUE TITLE
Profile creation: placeholder for profile image

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#572]
We are currently displaying what looks like a unicode fallback until the user enters username text. Should we just make this a question mark, or something else?

![image](https://github.com/user-attachments/assets/7a9ef9fb-da3a-4807-b674-d72177166ce4)

**Comment by darickdang** [comment]
If we're using SF Symbols to make this (I'm assuming this because I saw it in the symbols collection), we should either use the person.fill symbol or the photo symbol: 

person.fill:
![CleanShot 2024-08-27 at 23 23 56@2x](https://github.com/user-attachments/assets/f87f5f05-b23c-4a67-9550-bd443022583e)

photo:
![CleanShot 2024-08-27 at 23 22 22@2x](https://github.com/user-attachments/assets/17d84662-c66f-450c-a4ba-b843fde27cd6)

I think the "photo" option would work better since someone could upload a non-person photo for their pfp.

**Comment by lourou** [comment]
@darickdang I've used the photo icon as recommended and the corresponding icon in materials for Android. See screenshots below:

![IMG_1211](https://github.com/user-attachments/assets/4f25f08e-d86a-481e-a711-e7029d177245)
![IMG_1212](https://github.com/user-attachments/assets/d4a68cc2-363d-448b-8c19-03d107ac4ed3)

![Screenshot_1724854539](https://github.com/user-attachments/assets/f7d128e0-3276-4d3f-9528-e9458f95b55d)
![Screenshot_1724854587](https://github.com/user-attachments/assets/75eb5e72-d4ff-47bb-a5c6-4a6dc3627a87)
