### ISSUE TITLE
Group profile consent action still uses "block" and does not alert

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#592]
In this video, I show how "Block" alerts from the 1:1 profile page but not from the group profile page.

https://github.com/user-attachments/assets/cc6f53ae-4b3a-4f2e-a6e9-ce6db553dba9

Here's a markup with strings we can use, consistent with the "trash can" from the conversation list.

<img src="https://github.com/user-attachments/assets/f2a21f8e-7c27-4a04-8053-0e82f499fce8" width=350 />
<img src="https://github.com/user-attachments/assets/632860d3-0694-4217-ab79-a17197d90f12" width=350/>

**Comment by saulmc** [comment]
@lourou Let's also update the action sheet when you "Decline" a group invite from the consent module.

**Comment by lourou** [comment]
@saulmc I have added the ability to remove and restore profiles with a unified action-sheet, from the profile screen, and also from the group consent module.

The "view group" option is only accessible from the conversation list once the group is removed. This prevents a UI loop issue where the user could encounter problems on split screens like iPads (they could potentially do Profile > Removed chats > View only > Hit group profile, and press View only again, which would trigger the loop).

I have also created a screencast compilation of all cases for reference:

https://github.com/user-attachments/assets/88039efe-416c-4ec0-b0aa-4458f9d8101a

<img src="https://github.com/user-attachments/assets/fc152f62-0966-4f5e-a335-e3a3f80c1bf3" width="350" />

**Comment by lourou** [comment]
Thanks @saulmc!

The second screencast is a bit confusing because it generally goes back to the previous screen. In the screencast, the previous screen was the Removed Chats list (I removed a removed chat for demo, and this is possible because the group consent window in group chats is shown for `undefined`, `unknown` and `denied` consent values). If you're in the requests, it goes back to the updated requests list.
