### ISSUE TITLE
Spam tab shows "You might know" text

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#684]
<img src="https://github.com/user-attachments/assets/b45d7d5f-97a5-4148-bc8f-5204008248e8" width = 350/>

**Comment by lourou** [comment]
@saulmc I intentionally did that to maintain the same position in the conversation list and prevent vertical movement when using the segmented controller (see below). I'll push a change so that the text only appears on the first tab

![CleanShot 2024-09-06 at 08 56 37](https://github.com/user-attachments/assets/6bc2ca19-dd4c-4d24-91e4-1b09753cb40c)
