### ISSUE TITLE
App Icon Refresh

### ISSUE THREAD

**Issue by darickdang** [ephemeraHQ/converse-app#715]
- [x] iOS: change the app icons and the dev/preview app icons
- [x] iOS: implement and test the new splash screen on iPhone and iPad, both on portrait and landscape modes
- [ ] Android: change the app icons and the dev/preview app icons
- [ ] Android: implement and test the new splash screen

**App Store/Google Play updates**
- [ ] Change the app icon on App Store
- [ ] Change the app icon on Google Play

### Is your feature request related to a problem?

This is an app icon update recommendation to visually demonstrate that there will be upcoming changes to the app's design, brand, and look & feel.

### Describe the solution to the problem

**iOS:**

![App_store_1024_1x](https://github.com/user-attachments/assets/ea156db4-783c-4591-99ec-2fe666629520)

![Home Screen (iPhone 11 Pro Max)](https://github.com/user-attachments/assets/7d0b0f95-d95d-49e4-8749-669087d31675)

**Android:**

![ic_launcher_google_play](https://github.com/user-attachments/assets/4f5c9a09-b86d-4ba6-be1b-4d14020fddae)

![App Drawer (1080x2220)](https://github.com/user-attachments/assets/068c05ca-f3b6-49aa-9bdf-684c77311075)

Zip file for assets:

[ConverseIconExport.zip](https://github.com/user-attachments/files/16966693/ConverseIconExport.zip)

**Comment by lourou** [comment]
Hey @saulmc, I noticed that the splash screen icon is outdated since it was the old purple icon. I updated it with a new splash screen that I found in the source code. Take a look at it below in both light and dark modes. Let me know if it works for you. If not, could you provide a replacement splash for both light and dark modes with white and black backgrounds?

I created a Preview/Dev version of the app icon. This will help us differentiate it visually while working on it. @darickdang the dev app icon is only visible in dev and preview mode and is never shared with public users, not even on TestFlight.

### Dev App Icon

![iPad_App_76_2x](https://github.com/user-attachments/assets/59c35f01-9a96-4878-81b2-175d3473eb2c)

### Splash Screen

<img src="https://github.com/user-attachments/assets/eccd52c8-fb0f-48a3-8c38-65db412b591a" width="350" />
<img src="https://github.com/user-attachments/assets/42afbf8f-2283-43ad-bd76-ffad0956a055" width="350" />

**Comment by darickdang** [comment]
@lourou I used the official Material template to create a set of assets. Let me know if I missed anything!

![CleanShot 2024-09-13 at 08 54 35@2x](https://github.com/user-attachments/assets/c59e8b02-67a3-470e-b2ba-e15e279f2d14)

.zip of the assets: 
[newAndroid.zip](https://github.com/user-attachments/files/16996406/newAndroid.zip)

**Comment by darickdang** [comment]
@lourou 

And iOS splash screens:

Dark:
![SplashDark](https://github.com/user-attachments/assets/a61416f5-3632-4e47-b21e-9968a792faf5)

Light:
![SplashLight](https://github.com/user-attachments/assets/4624f0a4-422b-4325-8a70-b14f0e59bbfc)

Asset files: 
[SplashNew.zip](https://github.com/user-attachments/files/16996423/SplashNew.zip)
